# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

project_name: gno
release:
  github:
    owner: faanrm
    name: go-node

# Define actions to perform before the release.
before:
  hooks:
    # Update dependencies if using Go modules.
    - go mod tidy
    # Generate code if needed.
    - go generate ./...

# Define build configuration.
builds:
  - env:
      # Disable CGO for static binaries.
      - CGO_ENABLED=0
    goos:
      # Build for Linux, Windows, and macOS.
      - linux
      - windows
      - darwin

# Define archive formats and templates.
archives:
  - format: tar.gz
    # Customize the naming template for the archives.
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}
    id: default  # Ajout d'un identifiant unique pour cette archive
  - format: zip
    # Customize the naming template for Windows archives.
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}
    id: windows  # Ajout d'un identifiant unique pour cette archive

# Define changelog configuration.
changelog:
  sort: asc
  filters:
    exclude:
      # Exclude lines starting with "docs:" or "test:" from the changelog.
      - "^docs:"
      - "^test:"
